language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install tfp-nightly tfds-nightly numpy jaxlib jax tf-nightly --upgrade
  - pip install git+https://github.com/google/jax.git
  - pip install -e .
script:
  - set -e
  # - for f in tests/*.py; do python $f; done
  # TODO (DarrenZhang01): Replace the JAX support with TF support in the
  # rest of the test files (except `infinite_fcn`, `weight_space`,
  #                         `function_space` and `stax_test`), also deal with
  #                         errors in stax tests and infinite fcn tests.
  - python tests/function_space_test.py
  - python tests/weight_space_test.py
