language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install more-itertools numpy jaxlib tensorflow tensorflow-datasets --upgrade
  - pip install git+https://github.com/google/jax.git
  - pip install -e .
script:
  - set -e
  - for f in tests/*.py; do python $f; done

